import type { Metadata } from "next";
import {  Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import PixelBlast from "@/components/PixelBlast";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "700"],
});
export const metadata: Metadata = {
  title: "Hendra Sutrisno",
  description: "Generated by Hendra",
  icons: {
    icon: "/Logo.png", // ✅ Path favicon di folder public
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserrat.variable} antialiased`}
      >
       <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            duration: 4000,
            style: {
              background: "rgba(255, 255, 255, 0.85)",
              color: "#1f1f1f",
              padding: "16px 20px",
              fontSize: "15px",
              borderRadius: "10px",
              backdropFilter: "blur(10px)",
              boxShadow: "0 4px 20px rgba(0, 0, 0, 0.2)",
              fontWeight: 500,
              maxWidth: "400px",
            },
            success: {
              iconTheme: {
                primary: "#10B981", // green
                secondary: "#fff",
              },
            },
            error: {
              iconTheme: {
                primary: "#EF4444", // red
                secondary: "#fff",
              },
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
